(define error-vector (vector
256 'SQLITE_OK_LOAD_PERMANENTLY "not an error"
257 'SQLITE_ERROR_MISSING_COLLSEQ "SQL logic error"
261 'SQLITE_BUSY_RECOVERY "database is locked"
262 'SQLITE_LOCKED_SHAREDCACHE "database table is locked"
264 'SQLITE_READONLY_RECOVERY "attempt to write a readonly database"
266 'SQLITE_IOERR_READ "disk I/O error"
267 'SQLITE_CORRUPT_VTAB "database disk image is malformed"
270 'SQLITE_CANTOPEN_NOTEMPDIR "unable to open database file"
275 'SQLITE_CONSTRAINT_CHECK "constraint failed"
279 'SQLITE_AUTH_USER "authorization denied"
283 'SQLITE_NOTICE_RECOVER_WAL "notification message"
284 'SQLITE_WARNING_AUTOINDEX "warning message"
513 'SQLITE_ERROR_RETRY "SQL logic error"
516 'SQLITE_ABORT_ROLLBACK "abort due to ROLLBACK"
517 'SQLITE_BUSY_SNAPSHOT "database is locked"
518 'SQLITE_LOCKED_VTAB "database table is locked"
520 'SQLITE_READONLY_CANTLOCK "attempt to write a readonly database"
522 'SQLITE_IOERR_SHORT_READ "disk I/O error"
523 'SQLITE_CORRUPT_SEQUENCE "database disk image is malformed"
526 'SQLITE_CANTOPEN_ISDIR "unable to open database file"
531 'SQLITE_CONSTRAINT_COMMITHOOK "constraint failed"
539 'SQLITE_NOTICE_RECOVER_ROLLBACK "notification message"
769 'SQLITE_ERROR_SNAPSHOT "SQL logic error"
776 'SQLITE_READONLY_ROLLBACK "attempt to write a readonly database"
778 'SQLITE_IOERR_WRITE "disk I/O error"
782 'SQLITE_CANTOPEN_FULLPATH "unable to open database file"
787 'SQLITE_CONSTRAINT_FOREIGNKEY "constraint failed"
1032 'SQLITE_READONLY_DBMOVED "attempt to write a readonly database"
1034 'SQLITE_IOERR_FSYNC "disk I/O error"
1038 'SQLITE_CANTOPEN_CONVPATH "unable to open database file"
1043 'SQLITE_CONSTRAINT_FUNCTION "constraint failed"
1288 'SQLITE_READONLY_CANTINIT "attempt to write a readonly database"
1290 'SQLITE_IOERR_DIR_FSYNC "disk I/O error"
1294 'SQLITE_CANTOPEN_DIRTYWAL "unable to open database file"
1299 'SQLITE_CONSTRAINT_NOTNULL "constraint failed"
1544 'SQLITE_READONLY_DIRECTORY "attempt to write a readonly database"
1546 'SQLITE_IOERR_TRUNCATE "disk I/O error"
1555 'SQLITE_CONSTRAINT_PRIMARYKEY "constraint failed"
1802 'SQLITE_IOERR_FSTAT "disk I/O error"
1811 'SQLITE_CONSTRAINT_TRIGGER "constraint failed"
2058 'SQLITE_IOERR_UNLOCK "disk I/O error"
2067 'SQLITE_CONSTRAINT_UNIQUE "constraint failed"
2314 'SQLITE_IOERR_RDLOCK "disk I/O error"
2323 'SQLITE_CONSTRAINT_VTAB "constraint failed"
2570 'SQLITE_IOERR_DELETE "disk I/O error"
2579 'SQLITE_CONSTRAINT_ROWID "constraint failed"
2826 'SQLITE_IOERR_BLOCKED "disk I/O error"
3082 'SQLITE_IOERR_NOMEM "disk I/O error"
3338 'SQLITE_IOERR_ACCESS "disk I/O error"
3594 'SQLITE_IOERR_CHECKRESERVEDLOCK "disk I/O error"
3850 'SQLITE_IOERR_LOCK "disk I/O error"
4106 'SQLITE_IOERR_CLOSE "disk I/O error"
4362 'SQLITE_IOERR_DIR_CLOSE "disk I/O error"
4618 'SQLITE_IOERR_SHMOPEN "disk I/O error"
4874 'SQLITE_IOERR_SHMSIZE "disk I/O error"
5130 'SQLITE_IOERR_SHMLOCK "disk I/O error"
5386 'SQLITE_IOERR_SHMMAP "disk I/O error"
5642 'SQLITE_IOERR_SEEK "disk I/O error"
5898 'SQLITE_IOERR_DELETE_NOENT "disk I/O error"
6154 'SQLITE_IOERR_MMAP "disk I/O error"
6410 'SQLITE_IOERR_GETTEMPPATH "disk I/O error"
6666 'SQLITE_IOERR_CONVPATH "disk I/O error"
6922 'SQLITE_IOERR_VNODE "disk I/O error"
7178 'SQLITE_IOERR_AUTH "disk I/O error"
7434 'SQLITE_IOERR_BEGIN_ATOMIC "disk I/O error"
7690 'SQLITE_IOERR_COMMIT_ATOMIC "disk I/O error"
7946 'SQLITE_IOERR_ROLLBACK_ATOMIC "disk I/O error"
))
