(define errno-vector (vector
0 'ERROR_SUCCESS "Success"
1 'ERROR_INVALID_FUNCTION "Invalid function"
2 'ERROR_FILE_NOT_FOUND "File not found"
3 'ERROR_PATH_NOT_FOUND "Path not found"
4 'ERROR_TOO_MANY_OPEN_FILES "Too many open files"
5 'ERROR_ACCESS_DENIED "Access denied"
6 'ERROR_INVALID_HANDLE "Invalid handle"
7 'ERROR_ARENA_TRASHED "Memory trashed"
8 'ERROR_NOT_ENOUGH_MEMORY "Not enough memory"
9 'ERROR_INVALID_BLOCK "Invalid block"
10 'ERROR_BAD_ENVIRONMENT "Bad environment"
11 'ERROR_BAD_FORMAT "Bad format"
12 'ERROR_INVALID_ACCESS "Invalid access"
13 'ERROR_INVALID_DATA "Invalid data"
14 'ERROR_OUTOFMEMORY "Out of memory"
15 'ERROR_INVALID_DRIVE "Invalid drive"
16 'ERROR_CURRENT_DIRECTORY "Can't delete current directory"
17 'ERROR_NOT_SAME_DEVICE "Not same device"
18 'ERROR_NO_MORE_FILES "No more files"
19 'ERROR_WRITE_PROTECT "Write protected"
20 'ERROR_BAD_UNIT "Bad unit"
21 'ERROR_NOT_READY "Not ready"
22 'ERROR_BAD_COMMAND "Bad command"
23 'ERROR_CRC "CRC error"
24 'ERROR_BAD_LENGTH "Bad length"
25 'ERROR_SEEK "Seek error"
26 'ERROR_NOT_DOS_DISK "Not DOS disk"
27 'ERROR_SECTOR_NOT_FOUND "Sector not found"
28 'ERROR_OUT_OF_PAPER "Out of paper"
29 'ERROR_WRITE_FAULT "Write fault"
30 'ERROR_READ_FAULT "Read fault"
31 'ERROR_GEN_FAILURE "General failure"
32 'ERROR_SHARING_VIOLATION "Sharing violation"
33 'ERROR_LOCK_VIOLATION "Lock violation"
34 'ERROR_WRONG_DISK "Wrong disk"
36 'ERROR_SHARING_BUFFER_EXCEEDED "Sharing buffer exceeded"
38 'ERROR_HANDLE_EOF "End of file"
39 'ERROR_HANDLE_DISK_FULL "Disk full"
50 'ERROR_NOT_SUPPORTED "Request not supported"
51 'ERROR_REM_NOT_LIST "Remote machine not listening"
52 'ERROR_DUP_NAME "Duplicate network name"
53 'ERROR_BAD_NETPATH "Bad network path"
54 'ERROR_NETWORK_BUSY "Network busy"
55 'ERROR_DEV_NOT_EXIST "Device does not exist"
56 'ERROR_TOO_MANY_CMDS "Too many commands"
57 'ERROR_ADAP_HDW_ERR "Adapter hardware error"
58 'ERROR_BAD_NET_RESP "Bad network response"
59 'ERROR_UNEXP_NET_ERR "Unexpected network error"
60 'ERROR_BAD_REM_ADAP "Bad remote adapter"
61 'ERROR_PRINTQ_FULL "Print queue full"
62 'ERROR_NO_SPOOL_SPACE "No spool space"
63 'ERROR_PRINT_CANCELLED "Print canceled"
64 'ERROR_NETNAME_DELETED "Network name deleted"
65 'ERROR_NETWORK_ACCESS_DENIED "Network access denied"
66 'ERROR_BAD_DEV_TYPE "Bad device type"
67 'ERROR_BAD_NET_NAME "Bad network name"
68 'ERROR_TOO_MANY_NAMES "Too many network names"
69 'ERROR_TOO_MANY_SESS "Too many network sessions"
70 'ERROR_SHARING_PAUSED "Sharing paused"
71 'ERROR_REQ_NOT_ACCEP "Request not accepted"
72 'ERROR_REDIR_PAUSED "Redirector paused"
80 'ERROR_FILE_EXISTS "File exists"
82 'ERROR_CANNOT_MAKE "Cannot create"
83 'ERROR_FAIL_I24 "Int24 failure"
84 'ERROR_OUT_OF_STRUCTURES "Out of structures"
85 'ERROR_ALREADY_ASSIGNED "Already assigned"
86 'ERROR_INVALID_PASSWORD "Invalid password"
87 'ERROR_INVALID_PARAMETER "Invalid parameter"
88 'ERROR_NET_WRITE_FAULT "Net write fault"
89 'ERROR_NO_PROC_SLOTS "No process slots"
100 'ERROR_TOO_MANY_SEMAPHORES "Too many semaphores"
101 'ERROR_EXCL_SEM_ALREADY_OWNED "Exclusive semaphore already owned"
102 'ERROR_SEM_IS_SET "Semaphore is set"
103 'ERROR_TOO_MANY_SEM_REQUESTS "Too many semaphore requests"
104 'ERROR_INVALID_AT_INTERRUPT_TIME "Invalid at interrupt time"
105 'ERROR_SEM_OWNER_DIED "Semaphore owner died"
106 'ERROR_SEM_USER_LIMIT "Semaphore user limit"
107 'ERROR_DISK_CHANGE "Insert disk for drive %1"
108 'ERROR_DRIVE_LOCKED "Drive locked"
109 'ERROR_BROKEN_PIPE "Broken pipe"
110 'ERROR_OPEN_FAILED "Open failed"
111 'ERROR_BUFFER_OVERFLOW "Buffer overflow"
112 'ERROR_DISK_FULL "Disk full"
113 'ERROR_NO_MORE_SEARCH_HANDLES "No more search handles"
114 'ERROR_INVALID_TARGET_HANDLE "Invalid target handle"
117 'ERROR_INVALID_CATEGORY "Invalid IOCTL"
118 'ERROR_INVALID_VERIFY_SWITCH "Invalid verify switch"
119 'ERROR_BAD_DRIVER_LEVEL "Bad driver level"
120 'ERROR_CALL_NOT_IMPLEMENTED "Call not implemented"
121 'ERROR_SEM_TIMEOUT "Semaphore timeout"
122 'ERROR_INSUFFICIENT_BUFFER "Insufficient buffer"
123 'ERROR_INVALID_NAME "Invalid name"
124 'ERROR_INVALID_LEVEL "Invalid level"
125 'ERROR_NO_VOLUME_LABEL "No volume label"
126 'ERROR_MOD_NOT_FOUND "Module not found"
127 'ERROR_PROC_NOT_FOUND "Procedure not found"
128 'ERROR_WAIT_NO_CHILDREN "No children to wait for"
129 'ERROR_CHILD_NOT_COMPLETE "Child process has not completed"
130 'ERROR_DIRECT_ACCESS_HANDLE "Invalid use of direct access handle"
131 'ERROR_NEGATIVE_SEEK "Negative seek"
132 'ERROR_SEEK_ON_DEVICE "Seek error"
133 'ERROR_IS_JOIN_TARGET "Drive is a JOIN target"
134 'ERROR_IS_JOINED "Drive is already JOINed"
135 'ERROR_IS_SUBSTED "Drive is already SUBSTed"
136 'ERROR_NOT_JOINED "Drive is not JOINed"
137 'ERROR_NOT_SUBSTED "Drive is not SUBSTed"
138 'ERROR_JOIN_TO_JOIN "Attempt to JOIN onto a JOINed drive"
139 'ERROR_SUBST_TO_SUBST "Attempt to SUBST onto a SUBSTed drive"
140 'ERROR_JOIN_TO_SUBST "Attempt to JOIN to a SUBSTed drive"
141 'ERROR_SUBST_TO_JOIN "Attempt to SUBST to a JOINed drive"
142 'ERROR_BUSY_DRIVE "Drive is busy"
143 'ERROR_SAME_DRIVE "Same drive"
144 'ERROR_DIR_NOT_ROOT "Not top-level directory"
145 'ERROR_DIR_NOT_EMPTY "Directory is not empty"
146 'ERROR_IS_SUBST_PATH "Path is in use as a SUBST"
147 'ERROR_IS_JOIN_PATH "Path is in use as a JOIN"
148 'ERROR_PATH_BUSY "Path is busy"
149 'ERROR_IS_SUBST_TARGET "Already a SUBST target"
150 'ERROR_SYSTEM_TRACE "System trace not specified or disallowed"
151 'ERROR_INVALID_EVENT_COUNT "Event count for DosMuxSemWait incorrect"
152 'ERROR_TOO_MANY_MUXWAITERS "Too many waiters for DosMuxSemWait"
153 'ERROR_INVALID_LIST_FORMAT "DosSemMuxWait list invalid"
154 'ERROR_LABEL_TOO_LONG "Volume label too long"
155 'ERROR_TOO_MANY_TCBS "Too many TCBs"
156 'ERROR_SIGNAL_REFUSED "Signal refused"
157 'ERROR_DISCARDED "Segment discarded"
158 'ERROR_NOT_LOCKED "Segment not locked"
159 'ERROR_BAD_THREADID_ADDR "Bad thread ID address"
160 'ERROR_BAD_ARGUMENTS "Bad arguments to DosExecPgm"
161 'ERROR_BAD_PATHNAME "Path is invalid"
162 'ERROR_SIGNAL_PENDING "Signal pending"
164 'ERROR_MAX_THRDS_REACHED "Max system-wide thread count reached"
167 'ERROR_LOCK_FAILED "Lock failed"
170 'ERROR_BUSY "Resource in use"
173 'ERROR_CANCEL_VIOLATION "Cancel violation"
174 'ERROR_ATOMIC_LOCKS_NOT_SUPPORTED "Atomic locks not supported"
180 'ERROR_INVALID_SEGMENT_NUMBER "Invalid segment number"
182 'ERROR_INVALID_ORDINAL "Invalid ordinal for %1"
183 'ERROR_ALREADY_EXISTS "File already exists"
186 'ERROR_INVALID_FLAG_NUMBER "Invalid flag number"
187 'ERROR_SEM_NOT_FOUND "Semaphore name not found"
188 'ERROR_INVALID_STARTING_CODESEG "Invalid starting code segment for %1"
189 'ERROR_INVALID_STACKSEG "Invalid starting stack segment for %1"
190 'ERROR_INVALID_MODULETYPE "Invalid module type for %1"
191 'ERROR_INVALID_EXE_SIGNATURE "Invalid EXE signature in %1"
192 'ERROR_EXE_MARKED_INVALID "EXE %1 is marked invalid"
193 'ERROR_BAD_EXE_FORMAT "Bad EXE format for %1"
194 'ERROR_ITERATED_DATA_EXCEEDS_64k "Iterated data exceeds 64k in %1"
195 'ERROR_INVALID_MINALLOCSIZE "Invalid MinAllocSize in %1"
196 'ERROR_DYNLINK_FROM_INVALID_RING "Dynlink from invalid ring"
197 'ERROR_IOPL_NOT_ENABLED "IOPL not enabled"
198 'ERROR_INVALID_SEGDPL "Invalid SEGDPL in %1"
199 'ERROR_AUTODATASEG_EXCEEDS_64k "Auto data segment exceeds 64k"
200 'ERROR_RING2SEG_MUST_BE_MOVABLE "Ring 2 segment must be movable"
201 'ERROR_RELOC_CHAIN_XEEDS_SEGLIM "Relocation chain exceeds segment limit in %1"
202 'ERROR_INFLOOP_IN_RELOC_CHAIN "Infinite loop in relocation chain in %1"
203 'ERROR_ENVVAR_NOT_FOUND "Environment variable not found"
205 'ERROR_NO_SIGNAL_SENT "No signal sent"
206 'ERROR_FILENAME_EXCED_RANGE "File name is too long"
207 'ERROR_RING2_STACK_IN_USE "Ring 2 stack in use"
208 'ERROR_META_EXPANSION_TOO_LONG "Error in use of filename wildcards"
209 'ERROR_INVALID_SIGNAL_NUMBER "Invalid signal number"
210 'ERROR_THREAD_1_INACTIVE "Error setting signal handler"
212 'ERROR_LOCKED "Segment locked"
214 'ERROR_TOO_MANY_MODULES "Too many modules"
215 'ERROR_NESTING_NOT_ALLOWED "Nesting LoadModule calls not allowed"
216 'ERROR_EXE_MACHINE_TYPE_MISMATCH "Machine type mismatch"
230 'ERROR_BAD_PIPE "Bad pipe"
231 'ERROR_PIPE_BUSY "Pipe busy"
232 'ERROR_NO_DATA "Pipe closed"
233 'ERROR_PIPE_NOT_CONNECTED "Pipe not connected"
234 'ERROR_MORE_DATA "More data available"
240 'ERROR_VC_DISCONNECTED "Session canceled"
254 'ERROR_INVALID_EA_NAME "Invalid extended attribute name"
255 'ERROR_EA_LIST_INCONSISTENT "Extended attribute list inconsistent"
259 'ERROR_NO_MORE_ITEMS "No more data available"
266 'ERROR_CANNOT_COPY "Cannot use Copy API"
267 'ERROR_DIRECTORY "Directory name invalid"
275 'ERROR_EAS_DIDNT_FIT "Extended attributes didn't fit"
276 'ERROR_EA_FILE_CORRUPT "Extended attribute file corrupt"
277 'ERROR_EA_TABLE_FULL "Extended attribute table full"
278 'ERROR_INVALID_EA_HANDLE "Invalid extended attribute handle"
282 'ERROR_EAS_NOT_SUPPORTED "Extended attributes not supported"
288 'ERROR_NOT_OWNER "Mutex not owned by caller"
298 'ERROR_TOO_MANY_POSTS "Too many posts to semaphore"
299 'ERROR_PARTIAL_COPY "Read/WriteProcessMemory partially completed"
300 'ERROR_OPLOCK_NOT_GRANTED "The oplock wasn't granted"
301 'ERROR_INVALID_OPLOCK_PROTOCOL "Invalid oplock message received"
317 'ERROR_MR_MID_NOT_FOUND "Message 0x%1 not found in file %2"
487 'ERROR_INVALID_ADDRESS "Invalid address"
534 'ERROR_ARITHMETIC_OVERFLOW "Arithmetic overflow"
535 'ERROR_PIPE_CONNECTED "Pipe connected"
536 'ERROR_PIPE_LISTENING "Pipe listening"
994 'ERROR_EA_ACCESS_DENIED "Extended attribute access denied"
995 'ERROR_OPERATION_ABORTED "I/O operation aborted"
996 'ERROR_IO_INCOMPLETE "Overlapped I/O incomplete"
997 'ERROR_IO_PENDING "Overlapped I/O pending"
998 'ERROR_NOACCESS "No access to memory location"
999 'ERROR_SWAPERROR "Swap error"
1001 'ERROR_STACK_OVERFLOW "Stack overflow"
1002 'ERROR_INVALID_MESSAGE "Invalid message"
1003 'ERROR_CAN_NOT_COMPLETE "Cannot complete"
1004 'ERROR_INVALID_FLAGS "Invalid flags"
1005 'ERROR_UNRECOGNIZED_VOLUME "Unrecognized volume"
1006 'ERROR_FILE_INVALID "File invalid"
1007 'ERROR_FULLSCREEN_MODE "Cannot run full-screen"
1008 'ERROR_NO_TOKEN "Nonexistent token"
1009 'ERROR_BADDB "Registry corrupt"
1010 'ERROR_BADKEY "Invalid key"
1011 'ERROR_CANTOPEN "Can't open registry key"
1012 'ERROR_CANTREAD "Can't read registry key"
1013 'ERROR_CANTWRITE "Can't write registry key"
1014 'ERROR_REGISTRY_RECOVERED "Registry has been recovered"
1015 'ERROR_REGISTRY_CORRUPT "Registry is corrupt"
1016 'ERROR_REGISTRY_IO_FAILED "I/O to registry failed"
1017 'ERROR_NOT_REGISTRY_FILE "Not registry file"
1018 'ERROR_KEY_DELETED "Key deleted"
1019 'ERROR_NO_LOG_SPACE "No registry log space"
1020 'ERROR_KEY_HAS_CHILDREN "Registry key has subkeys"
1021 'ERROR_CHILD_MUST_BE_VOLATILE "Subkey must be volatile"
1022 'ERROR_NOTIFY_ENUM_DIR "Notify change request in progress"
1051 'ERROR_DEPENDENT_SERVICES_RUNNING "Dependent services are running"
1052 'ERROR_INVALID_SERVICE_CONTROL "Invalid service control"
1053 'ERROR_SERVICE_REQUEST_TIMEOUT "Service request timeout"
1054 'ERROR_SERVICE_NO_THREAD "Cannot create service thread"
1055 'ERROR_SERVICE_DATABASE_LOCKED "Service database locked"
1056 'ERROR_SERVICE_ALREADY_RUNNING "Service already running"
1057 'ERROR_INVALID_SERVICE_ACCOUNT "Invalid service account"
1058 'ERROR_SERVICE_DISABLED "Service is disabled"
1059 'ERROR_CIRCULAR_DEPENDENCY "Circular dependency"
1060 'ERROR_SERVICE_DOES_NOT_EXIST "Service does not exist"
1061 'ERROR_SERVICE_CANNOT_ACCEPT_CTRL "Service cannot accept control message"
1062 'ERROR_SERVICE_NOT_ACTIVE "Service not active"
1063 'ERROR_FAILED_SERVICE_CONTROLLER_CONNECT "Service controller connect failed"
1064 'ERROR_EXCEPTION_IN_SERVICE "Exception in service"
1065 'ERROR_DATABASE_DOES_NOT_EXIST "Database does not exist"
1066 'ERROR_SERVICE_SPECIFIC_ERROR "Service-specific error"
1067 'ERROR_PROCESS_ABORTED "Process aborted"
1068 'ERROR_SERVICE_DEPENDENCY_FAIL "Service dependency failed"
1069 'ERROR_SERVICE_LOGON_FAILED "Service login failed"
1070 'ERROR_SERVICE_START_HANG "Service start-hang"
1071 'ERROR_INVALID_SERVICE_LOCK "Invalid service lock"
1072 'ERROR_SERVICE_MARKED_FOR_DELETE "Service marked for delete"
1073 'ERROR_SERVICE_EXISTS "Service exists"
1074 'ERROR_ALREADY_RUNNING_LKG "System running last-known-good config"
1075 'ERROR_SERVICE_DEPENDENCY_DELETED "Service dependency deleted"
1076 'ERROR_BOOT_ALREADY_ACCEPTED "Boot already accepted as last-good config"
1077 'ERROR_SERVICE_NEVER_STARTED "Service not started since last boot"
1078 'ERROR_DUPLICATE_SERVICE_NAME "Duplicate service name"
1079 'ERROR_DIFFERENT_SERVICE_ACCOUNT "Different service account"
1080 'ERROR_CANNOT_DETECT_DRIVER_FAILURE "Driver failure cannot be detected"
1081 'ERROR_CANNOT_DETECT_PROCESS_ABORT "Process abort cannot be detected"
1082 'ERROR_NO_RECOVERY_PROGRAM "No recovery program for service"
1083 'ERROR_SERVICE_NOT_IN_EXE "Service not implemented by exe"
1100 'ERROR_END_OF_MEDIA "End of media"
1101 'ERROR_FILEMARK_DETECTED "Filemark detected"
1102 'ERROR_BEGINNING_OF_MEDIA "Beginning of media"
1103 'ERROR_SETMARK_DETECTED "Setmark detected"
1104 'ERROR_NO_DATA_DETECTED "No data detected"
1105 'ERROR_PARTITION_FAILURE "Partition failure"
1106 'ERROR_INVALID_BLOCK_LENGTH "Invalid block length"
1107 'ERROR_DEVICE_NOT_PARTITIONED "Device not partitioned"
1108 'ERROR_UNABLE_TO_LOCK_MEDIA "Unable to lock media"
1109 'ERROR_UNABLE_TO_UNLOAD_MEDIA "Unable to unload media"
1110 'ERROR_MEDIA_CHANGED "Media changed"
1111 'ERROR_BUS_RESET "I/O bus reset"
1112 'ERROR_NO_MEDIA_IN_DRIVE "No media in drive"
1113 'ERROR_NO_UNICODE_TRANSLATION "No Unicode translation"
1114 'ERROR_DLL_INIT_FAILED "DLL initialization failed"
1115 'ERROR_SHUTDOWN_IN_PROGRESS "Shutdown in progress"
1116 'ERROR_NO_SHUTDOWN_IN_PROGRESS "No shutdown in progress"
1117 'ERROR_IO_DEVICE "I/O device error"
1118 'ERROR_SERIAL_NO_DEVICE "No serial devices found"
1119 'ERROR_IRQ_BUSY "Shared IRQ busy"
1120 'ERROR_MORE_WRITES "Serial I/O completed"
1121 'ERROR_COUNTER_TIMEOUT "Serial I/O counter timeout"
1122 'ERROR_FLOPPY_ID_MARK_NOT_FOUND "Floppy ID address mark not found"
1123 'ERROR_FLOPPY_WRONG_CYLINDER "Floppy reports wrong cylinder"
1124 'ERROR_FLOPPY_UNKNOWN_ERROR "Unknown floppy error"
1125 'ERROR_FLOPPY_BAD_REGISTERS "Floppy registers inconsistent"
1126 'ERROR_DISK_RECALIBRATE_FAILED "Hard disk recalibrate failed"
1127 'ERROR_DISK_OPERATION_FAILED "Hard disk operation failed"
1128 'ERROR_DISK_RESET_FAILED "Hard disk reset failed"
1129 'ERROR_EOM_OVERFLOW "End of tape media"
1130 'ERROR_NOT_ENOUGH_SERVER_MEMORY "Not enough server memory"
1131 'ERROR_POSSIBLE_DEADLOCK "Possible deadlock"
1132 'ERROR_MAPPED_ALIGNMENT "Incorrect alignment"
1140 'ERROR_SET_POWER_STATE_VETOED "Set-power-state vetoed"
1141 'ERROR_SET_POWER_STATE_FAILED "Set-power-state failed"
1142 'ERROR_TOO_MANY_LINKS "Too many links"
1150 'ERROR_OLD_WIN_VERSION "Newer windows version needed"
1151 'ERROR_APP_WRONG_OS "Wrong operating system"
1152 'ERROR_SINGLE_INSTANCE_APP "Single-instance application"
1153 'ERROR_RMODE_APP "Real-mode application"
1154 'ERROR_INVALID_DLL "Invalid DLL"
1155 'ERROR_NO_ASSOCIATION "No associated application"
1156 'ERROR_DDE_FAIL "DDE failure"
1157 'ERROR_DLL_NOT_FOUND "DLL not found"
1158 'ERROR_NO_MORE_USER_HANDLES "Out of user handles"
1159 'ERROR_MESSAGE_SYNC_ONLY "Message can only be used in synchronous calls"
1160 'ERROR_SOURCE_ELEMENT_EMPTY "The source element is empty"
1161 'ERROR_DESTINATION_ELEMENT_FULL "The destination element is full"
1162 'ERROR_ILLEGAL_ELEMENT_ADDRESS "The element address is invalid"
1163 'ERROR_MAGAZINE_NOT_PRESENT "The magazine is not present"
1164 'ERROR_DEVICE_REINITIALIZATION_NEEDED "The device needs reinitialization"
1165 'ERROR_DEVICE_REQUIRES_CLEANING "The device requires cleaning"
1166 'ERROR_DEVICE_DOOR_OPEN "The device door is open"
1167 'ERROR_DEVICE_NOT_CONNECTED "The device is not connected"
1168 'ERROR_NOT_FOUND "Element not found"
1169 'ERROR_NO_MATCH "No match found"
1170 'ERROR_SET_NOT_FOUND "Property set not found"
1171 'ERROR_POINT_NOT_FOUND "Point not found"
1172 'ERROR_NO_TRACKING_SERVICE "No running tracking service"
1173 'ERROR_NO_VOLUME_ID "No such volume ID"
1175 'ERROR_UNABLE_TO_REMOVE_REPLACED "Unable to remove the file to be replaced"
1176 'ERROR_UNABLE_TO_MOVE_REPLACEMENT "Unable to move the replacement file into place"
1177 'ERROR_UNABLE_TO_MOVE_REPLACEMENT_2 "Moving the replacement file failed"
1178 'ERROR_JOURNAL_DELETE_IN_PROGRESS "The journal is being deleted"
1179 'ERROR_JOURNAL_NOT_ACTIVE "The journal is not active"
1180 'ERROR_POTENTIAL_FILE_FOUND "Potential matching file found"
1181 'ERROR_JOURNAL_ENTRY_DELETED "The journal entry was deleted"
1200 'ERROR_BAD_DEVICE "Invalid device name"
1201 'ERROR_CONNECTION_UNAVAIL "Connection unavailable"
1202 'ERROR_DEVICE_ALREADY_REMEMBERED "Device already remembered"
1203 'ERROR_NO_NET_OR_BAD_PATH "No network or bad path"
1204 'ERROR_BAD_PROVIDER "Invalid network provider name"
1205 'ERROR_CANNOT_OPEN_PROFILE "Cannot open network connection profile"
1206 'ERROR_BAD_PROFILE "Corrupt network connection profile"
1207 'ERROR_NOT_CONTAINER "Not a container"
1208 'ERROR_EXTENDED_ERROR "Extended error"
1209 'ERROR_INVALID_GROUPNAME "Invalid group name"
1210 'ERROR_INVALID_COMPUTERNAME "Invalid computer name"
1211 'ERROR_INVALID_EVENTNAME "Invalid event name"
1212 'ERROR_INVALID_DOMAINNAME "Invalid domain name"
1213 'ERROR_INVALID_SERVICENAME "Invalid service name"
1214 'ERROR_INVALID_NETNAME "Invalid network name"
1215 'ERROR_INVALID_SHARENAME "Invalid share name"
1216 'ERROR_INVALID_PASSWORDNAME "Invalid password"
1217 'ERROR_INVALID_MESSAGENAME "Invalid message name"
1218 'ERROR_INVALID_MESSAGEDEST "Invalid message destination"
1219 'ERROR_SESSION_CREDENTIAL_CONFLICT "Session credential conflict"
1220 'ERROR_REMOTE_SESSION_LIMIT_EXCEEDED "Remote session limit exceeded"
1221 'ERROR_DUP_DOMAINNAME "Duplicate domain or workgroup name"
1222 'ERROR_NO_NETWORK "No network"
1223 'ERROR_CANCELLED "Operation canceled by user"
1224 'ERROR_USER_MAPPED_FILE "File has a user-mapped section"
1225 'ERROR_CONNECTION_REFUSED "Connection refused"
1226 'ERROR_GRACEFUL_DISCONNECT "Connection gracefully closed"
1227 'ERROR_ADDRESS_ALREADY_ASSOCIATED "Address already associated with transport endpoint"
1228 'ERROR_ADDRESS_NOT_ASSOCIATED "Address not associated with transport endpoint"
1229 'ERROR_CONNECTION_INVALID "Connection invalid"
1230 'ERROR_CONNECTION_ACTIVE "Connection is active"
1231 'ERROR_NETWORK_UNREACHABLE "Network unreachable"
1232 'ERROR_HOST_UNREACHABLE "Host unreachable"
1233 'ERROR_PROTOCOL_UNREACHABLE "Protocol unreachable"
1234 'ERROR_PORT_UNREACHABLE "Port unreachable"
1235 'ERROR_REQUEST_ABORTED "Request aborted"
1236 'ERROR_CONNECTION_ABORTED "Connection aborted"
1237 'ERROR_RETRY "Please retry operation"
1238 'ERROR_CONNECTION_COUNT_LIMIT "Connection count limit reached"
1239 'ERROR_LOGIN_TIME_RESTRICTION "Login time restriction"
1240 'ERROR_LOGIN_WKSTA_RESTRICTION "Login workstation restriction"
1241 'ERROR_INCORRECT_ADDRESS "Incorrect network address"
1242 'ERROR_ALREADY_REGISTERED "Service already registered"
1243 'ERROR_SERVICE_NOT_FOUND "Service not found"
1244 'ERROR_NOT_AUTHENTICATED "User not authenticated"
1245 'ERROR_NOT_LOGGED_ON "User not logged on"
1246 'ERROR_CONTINUE "Continue work in progress"
1247 'ERROR_ALREADY_INITIALIZED "Already initialized"
1248 'ERROR_NO_MORE_DEVICES "No more local devices"
1249 'ERROR_NO_SUCH_SITE "The site does not exist"
1250 'ERROR_DOMAIN_CONTROLLER_EXISTS "The domain controller already exists"
1251 'ERROR_ONLY_IF_CONNECTED "Supported only when connected"
1252 'ERROR_OVERRIDE_NOCHANGES "Perform operation even when nothing changed"
1253 'ERROR_BAD_USER_PROFILE "The user profile is invalid"
1254 'ERROR_NOT_SUPPORTED_ON_SBS "Not supported on Small Business Server"
1300 'ERROR_NOT_ALL_ASSIGNED "Not all privileges assigned"
1301 'ERROR_SOME_NOT_MAPPED "Some security IDs not mapped"
1302 'ERROR_NO_QUOTAS_FOR_ACCOUNT "No quotas for account"
1303 'ERROR_LOCAL_USER_SESSION_KEY "Local user session key"
1304 'ERROR_NULL_LM_PASSWORD "Password too complex for LM"
1305 'ERROR_UNKNOWN_REVISION "Unknown revision"
1306 'ERROR_REVISION_MISMATCH "Incompatible revision levels"
1307 'ERROR_INVALID_OWNER "Invalid owner"
1308 'ERROR_INVALID_PRIMARY_GROUP "Invalid primary group"
1309 'ERROR_NO_IMPERSONATION_TOKEN "No impersonation token"
1310 'ERROR_CANT_DISABLE_MANDATORY "Can't disable mandatory group"
1311 'ERROR_NO_LOGON_SERVERS "No logon servers available"
1312 'ERROR_NO_SUCH_LOGON_SESSION "No such logon session"
1313 'ERROR_NO_SUCH_PRIVILEGE "No such privilege"
1314 'ERROR_PRIVILEGE_NOT_HELD "Privilege not held"
1315 'ERROR_INVALID_ACCOUNT_NAME "Invalid account name"
1316 'ERROR_USER_EXISTS "User already exists"
1317 'ERROR_NO_SUCH_USER "No such user"
1318 'ERROR_GROUP_EXISTS "Group already exists"
1319 'ERROR_NO_SUCH_GROUP "No such group"
1320 'ERROR_MEMBER_IN_GROUP "User already in group"
1321 'ERROR_MEMBER_NOT_IN_GROUP "User not in group"
1322 'ERROR_LAST_ADMIN "Can't delete last admin user"
1323 'ERROR_WRONG_PASSWORD "Wrong password"
1324 'ERROR_ILL_FORMED_PASSWORD "Ill-formed password"
1325 'ERROR_PASSWORD_RESTRICTION "Password restriction"
1326 'ERROR_LOGON_FAILURE "Logon failure"
1327 'ERROR_ACCOUNT_RESTRICTION "Account restriction"
1328 'ERROR_INVALID_LOGON_HOURS "Invalid logon hours"
1329 'ERROR_INVALID_WORKSTATION "Invalid workstation"
1330 'ERROR_PASSWORD_EXPIRED "Password expired"
1331 'ERROR_ACCOUNT_DISABLED "Account disabled"
1332 'ERROR_NONE_MAPPED "No security ID mapped"
1333 'ERROR_TOO_MANY_LUIDS_REQUESTED "Too many LUIDs requested"
1334 'ERROR_LUIDS_EXHAUSTED "LUIDs exhausted"
1335 'ERROR_INVALID_SUB_AUTHORITY "Invalid sub authority"
1336 'ERROR_INVALID_ACL "Invalid ACL"
1337 'ERROR_INVALID_SID "Invalid SID"
1338 'ERROR_INVALID_SECURITY_DESCR "Invalid security descriptor"
1340 'ERROR_BAD_INHERITANCE_ACL "Bad inherited ACL"
1341 'ERROR_SERVER_DISABLED "Server disabled"
1342 'ERROR_SERVER_NOT_DISABLED "Server not disabled"
1343 'ERROR_INVALID_ID_AUTHORITY "Invalid ID authority"
1344 'ERROR_ALLOTTED_SPACE_EXCEEDED "Allotted space exceeded"
1345 'ERROR_INVALID_GROUP_ATTRIBUTES "Invalid group attributes"
1346 'ERROR_BAD_IMPERSONATION_LEVEL "Bad impersonation level"
1347 'ERROR_CANT_OPEN_ANONYMOUS "Can't open anonymous security token"
1348 'ERROR_BAD_VALIDATION_CLASS "Bad validation class"
1349 'ERROR_BAD_TOKEN_TYPE "Bad token type"
1350 'ERROR_NO_SECURITY_ON_OBJECT "No security on object"
1351 'ERROR_CANT_ACCESS_DOMAIN_INFO "Can't access domain information"
1352 'ERROR_INVALID_SERVER_STATE "Invalid server state"
1353 'ERROR_INVALID_DOMAIN_STATE "Invalid domain state"
1354 'ERROR_INVALID_DOMAIN_ROLE "Invalid domain role"
1355 'ERROR_NO_SUCH_DOMAIN "No such domain"
1356 'ERROR_DOMAIN_EXISTS "Domain already exists"
1357 'ERROR_DOMAIN_LIMIT_EXCEEDED "Domain limit exceeded"
1358 'ERROR_INTERNAL_DB_CORRUPTION "Internal database corruption"
1359 'ERROR_INTERNAL_ERROR "Internal error"
1360 'ERROR_GENERIC_NOT_MAPPED "Generic access types not mapped"
1361 'ERROR_BAD_DESCRIPTOR_FORMAT "Bad descriptor format"
1362 'ERROR_NOT_LOGON_PROCESS "Not a logon process"
1363 'ERROR_LOGON_SESSION_EXISTS "Logon session ID exists"
1364 'ERROR_NO_SUCH_PACKAGE "Unknown authentication package"
1365 'ERROR_BAD_LOGON_SESSION_STATE "Bad logon session state"
1366 'ERROR_LOGON_SESSION_COLLISION "Logon session ID collision"
1367 'ERROR_INVALID_LOGON_TYPE "Invalid logon type"
1368 'ERROR_CANNOT_IMPERSONATE "Cannot impersonate"
1369 'ERROR_RXACT_INVALID_STATE "Invalid transaction state"
1370 'ERROR_RXACT_COMMIT_FAILURE "Security DB commit failure"
1371 'ERROR_SPECIAL_ACCOUNT "Account is built-in"
1372 'ERROR_SPECIAL_GROUP "Group is built-in"
1373 'ERROR_SPECIAL_USER "User is built-in"
1374 'ERROR_MEMBERS_PRIMARY_GROUP "Group is primary for user"
1375 'ERROR_TOKEN_ALREADY_IN_USE "Token already in use"
1376 'ERROR_NO_SUCH_ALIAS "No such local group"
1377 'ERROR_MEMBER_NOT_IN_ALIAS "User not in local group"
1378 'ERROR_MEMBER_IN_ALIAS "User already in local group"
1379 'ERROR_ALIAS_EXISTS "Local group already exists"
1380 'ERROR_LOGON_NOT_GRANTED "Logon type not granted"
1381 'ERROR_TOO_MANY_SECRETS "Too many secrets"
1382 'ERROR_SECRET_TOO_LONG "Secret too long"
1383 'ERROR_INTERNAL_DB_ERROR "Internal security DB error"
1384 'ERROR_TOO_MANY_CONTEXT_IDS "Too many context IDs"
1385 'ERROR_LOGON_TYPE_NOT_GRANTED "Logon type not granted"
1386 'ERROR_NT_CROSS_ENCRYPTION_REQUIRED "Cross-encrypted NT password required"
1387 'ERROR_NO_SUCH_MEMBER "No such member"
1388 'ERROR_INVALID_MEMBER "Invalid member"
1389 'ERROR_TOO_MANY_SIDS "Too many SIDs"
1390 'ERROR_LM_CROSS_ENCRYPTION_REQUIRED "Cross-encrypted LM password required"
1391 'ERROR_NO_INHERITANCE "No inheritable components"
1392 'ERROR_FILE_CORRUPT "File or directory corrupt"
1393 'ERROR_DISK_CORRUPT "Disk is corrupt"
1394 'ERROR_NO_USER_SESSION_KEY "No user session key"
1395 'ERROR_LICENSE_QUOTA_EXCEEDED "License quota exceeded"
1396 'ERROR_WRONG_TARGET_NAME "Wrong target name"
1397 'ERROR_MUTUAL_AUTH_FAILED "Mutual authentication failed"
1398 'ERROR_TIME_SKEW "Time skew between client and server"
1400 'ERROR_INVALID_WINDOW_HANDLE "Invalid window handle"
1401 'ERROR_INVALID_MENU_HANDLE "Invalid menu handle"
1402 'ERROR_INVALID_CURSOR_HANDLE "Invalid cursor handle"
1403 'ERROR_INVALID_ACCEL_HANDLE "Invalid accelerator table handle"
1404 'ERROR_INVALID_HOOK_HANDLE "Invalid hook handle"
1405 'ERROR_INVALID_DWP_HANDLE "Invalid DWP handle"
1406 'ERROR_TLW_WITH_WSCHILD "Can't create top-level child window"
1407 'ERROR_CANNOT_FIND_WND_CLASS "Can't find window class"
1408 'ERROR_WINDOW_OF_OTHER_THREAD "Window owned by another thread"
1409 'ERROR_HOTKEY_ALREADY_REGISTERED "Hotkey already registered"
1410 'ERROR_CLASS_ALREADY_EXISTS "Class already exists"
1411 'ERROR_CLASS_DOES_NOT_EXIST "Class does not exist"
1412 'ERROR_CLASS_HAS_WINDOWS "Class has open windows"
1413 'ERROR_INVALID_INDEX "Invalid index"
1414 'ERROR_INVALID_ICON_HANDLE "Invalid icon handle"
1415 'ERROR_PRIVATE_DIALOG_INDEX "Private dialog index"
1416 'ERROR_LISTBOX_ID_NOT_FOUND "List box ID not found"
1417 'ERROR_NO_WILDCARD_CHARACTERS "No wildcard characters"
1418 'ERROR_CLIPBOARD_NOT_OPEN "Clipboard not open"
1419 'ERROR_HOTKEY_NOT_REGISTERED "Hotkey not registered"
1420 'ERROR_WINDOW_NOT_DIALOG "Not a dialog window"
1421 'ERROR_CONTROL_ID_NOT_FOUND "Control ID not found"
1422 'ERROR_INVALID_COMBOBOX_MESSAGE "Invalid combo box message"
1423 'ERROR_WINDOW_NOT_COMBOBOX "Not a combo box window"
1424 'ERROR_INVALID_EDIT_HEIGHT "Invalid edit height"
1425 'ERROR_DC_NOT_FOUND "DC not found"
1426 'ERROR_INVALID_HOOK_FILTER "Invalid hook filter"
1427 'ERROR_INVALID_FILTER_PROC "Invalid filter procedure"
1428 'ERROR_HOOK_NEEDS_HMOD "Hook procedure needs module handle"
1429 'ERROR_GLOBAL_ONLY_HOOK "Global-only hook procedure"
1430 'ERROR_JOURNAL_HOOK_SET "Journal hook already set"
1431 'ERROR_HOOK_NOT_INSTALLED "Hook procedure not installed"
1432 'ERROR_INVALID_LB_MESSAGE "Invalid list box message"
1433 'ERROR_SETCOUNT_ON_BAD_LB "Invalid LB_SETCOUNT sent"
1434 'ERROR_LB_WITHOUT_TABSTOPS "No tab stops on this list box"
1435 'ERROR_DESTROY_OBJECT_OF_OTHER_THREAD "Can't destroy object owned by another thread"
1436 'ERROR_CHILD_WINDOW_MENU "Child window menus not allowed"
1437 'ERROR_NO_SYSTEM_MENU "Window has no system menu"
1438 'ERROR_INVALID_MSGBOX_STYLE "Invalid message box style"
1439 'ERROR_INVALID_SPI_VALUE "Invalid SPI parameter"
1440 'ERROR_SCREEN_ALREADY_LOCKED "Screen already locked"
1441 'ERROR_HWNDS_HAVE_DIFF_PARENT "Window handles have different parents"
1442 'ERROR_NOT_CHILD_WINDOW "Not a child window"
1443 'ERROR_INVALID_GW_COMMAND "Invalid GW command"
1444 'ERROR_INVALID_THREAD_ID "Invalid thread ID"
1445 'ERROR_NON_MDICHILD_WINDOW "Not an MDI child window"
1446 'ERROR_POPUP_ALREADY_ACTIVE "Popup menu already active"
1447 'ERROR_NO_SCROLLBARS "No scrollbars"
1448 'ERROR_INVALID_SCROLLBAR_RANGE "Invalid scrollbar range"
1449 'ERROR_INVALID_SHOWWIN_COMMAND "Invalid ShowWin command"
1450 'ERROR_NO_SYSTEM_RESOURCES "No system resources"
1451 'ERROR_NONPAGED_SYSTEM_RESOURCES "No non-paged system resources"
1452 'ERROR_PAGED_SYSTEM_RESOURCES "No paged system resources"
1453 'ERROR_WORKING_SET_QUOTA "No working set quota"
1454 'ERROR_PAGEFILE_QUOTA "No page file quota"
1455 'ERROR_COMMITMENT_LIMIT "Exceeded commitment limit"
1456 'ERROR_MENU_ITEM_NOT_FOUND "Menu item not found"
1457 'ERROR_INVALID_KEYBOARD_HANDLE "Invalid keyboard handle"
1458 'ERROR_HOOK_TYPE_NOT_ALLOWED "Hook type not allowed"
1459 'ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION "Interactive window station required"
1460 'ERROR_TIMEOUT "Timeout"
1461 'ERROR_INVALID_MONITOR_HANDLE "Invalid monitor handle"
1500 'ERROR_EVENTLOG_FILE_CORRUPT "Event log file corrupt"
1501 'ERROR_EVENTLOG_CANT_START "Event log can't start"
1502 'ERROR_LOG_FILE_FULL "Event log file full"
1503 'ERROR_EVENTLOG_FILE_CHANGED "Event log file changed"
1601 'ERROR_INSTALL_SERVICE_FAILURE "Installer service failed"
1602 'ERROR_INSTALL_USEREXIT "Installation aborted by user"
1603 'ERROR_INSTALL_FAILURE "Installation failure"
1604 'ERROR_INSTALL_SUSPEND "Installation suspended"
1605 'ERROR_UNKNOWN_PRODUCT "Unknown product"
1606 'ERROR_UNKNOWN_FEATURE "Unknown feature"
1607 'ERROR_UNKNOWN_COMPONENT "Unknown component"
1608 'ERROR_UNKNOWN_PROPERTY "Unknown property"
1609 'ERROR_INVALID_HANDLE_STATE "Invalid handle state"
1610 'ERROR_BAD_CONFIGURATION "Bad configuration"
1611 'ERROR_INDEX_ABSENT "Index is missing"
1612 'ERROR_INSTALL_SOURCE_ABSENT "Installation source is missing"
1613 'ERROR_INSTALL_PACKAGE_VERSION "Wrong installation package version"
1614 'ERROR_PRODUCT_UNINSTALLED "Product uninstalled"
1615 'ERROR_BAD_QUERY_SYNTAX "Invalid query syntax"
1616 'ERROR_INVALID_FIELD "Invalid field"
1617 'ERROR_DEVICE_REMOVED "Device removed"
1618 'ERROR_INSTALL_ALREADY_RUNNING "Installation already running"
1619 'ERROR_INSTALL_PACKAGE_OPEN_FAILED "Installation package failed to open"
1620 'ERROR_INSTALL_PACKAGE_INVALID "Installation package is invalid"
1621 'ERROR_INSTALL_UI_FAILURE "Installer user interface failed"
1622 'ERROR_INSTALL_LOG_FAILURE "Failed to open installation log file"
1623 'ERROR_INSTALL_LANGUAGE_UNSUPPORTED "Installation language not supported"
1624 'ERROR_INSTALL_TRANSFORM_FAILURE "Installation transform failed to apply"
1625 'ERROR_INSTALL_PACKAGE_REJECTED "Installation package rejected"
1626 'ERROR_FUNCTION_NOT_CALLED "Function could not be called"
1627 'ERROR_FUNCTION_FAILED "Function failed"
1628 'ERROR_INVALID_TABLE "Invalid table"
1629 'ERROR_DATATYPE_MISMATCH "Data type mismatch"
1630 'ERROR_UNSUPPORTED_TYPE "Unsupported type"
1631 'ERROR_CREATE_FAILED "Creation failed"
1632 'ERROR_INSTALL_TEMP_UNWRITABLE "Temporary directory not writable"
1633 'ERROR_INSTALL_PLATFORM_UNSUPPORTED "Installation platform not supported"
1634 'ERROR_INSTALL_NOTUSED "Installer not used"
1635 'ERROR_PATCH_PACKAGE_OPEN_FAILED "Failed to open the patch package"
1636 'ERROR_PATCH_PACKAGE_INVALID "Invalid patch package"
1637 'ERROR_PATCH_PACKAGE_UNSUPPORTED "Unsupported patch package"
1638 'ERROR_PRODUCT_VERSION "Another version is installed"
1639 'ERROR_INVALID_COMMAND_LINE "Invalid command line"
1640 'ERROR_INSTALL_REMOTE_DISALLOWED "Remote installation not allowed"
1641 'ERROR_SUCCESS_REBOOT_INITIATED "Reboot initiated after successful install"
1784 'ERROR_INVALID_USER_BUFFER "Invalid user buffer"
1785 'ERROR_UNRECOGNIZED_MEDIA "Unrecognized media"
1786 'ERROR_NO_TRUST_LSA_SECRET "No trust secret"
1787 'ERROR_NO_TRUST_SAM_ACCOUNT "No trust SAM account"
1788 'ERROR_TRUSTED_DOMAIN_FAILURE "Trusted domain failure"
1789 'ERROR_TRUSTED_RELATIONSHIP_FAILURE "Trusted relationship failure"
1790 'ERROR_TRUST_FAILURE "Trust logon failure"
1792 'ERROR_NETLOGON_NOT_STARTED "NETLOGON is not started"
1793 'ERROR_ACCOUNT_EXPIRED "Account expired"
1794 'ERROR_REDIRECTOR_HAS_OPEN_HANDLES "Redirector has open handles"
1795 'ERROR_PRINTER_DRIVER_ALREADY_INSTALLED "Printer driver already installed"
1796 'ERROR_UNKNOWN_PORT "Unknown port"
1797 'ERROR_UNKNOWN_PRINTER_DRIVER "Unknown printer driver"
1798 'ERROR_UNKNOWN_PRINTPROCESSOR "Unknown print processor"
1799 'ERROR_INVALID_SEPARATOR_FILE "Invalid separator file"
1800 'ERROR_INVALID_PRIORITY "Invalid priority"
1801 'ERROR_INVALID_PRINTER_NAME "Invalid printer name"
1802 'ERROR_PRINTER_ALREADY_EXISTS "Printer already exists"
1803 'ERROR_INVALID_PRINTER_COMMAND "Invalid printer command"
1804 'ERROR_INVALID_DATATYPE "Invalid data type"
1805 'ERROR_INVALID_ENVIRONMENT "Invalid environment"
1807 'ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT "Can't log on with inter-domain trust account"
1808 'ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT "Can't log on with workstation trust account"
1809 'ERROR_NOLOGON_SERVER_TRUST_ACCOUNT "Can't log on with server trust account"
1810 'ERROR_DOMAIN_TRUST_INCONSISTENT "Domain trust information inconsistent"
1811 'ERROR_SERVER_HAS_OPEN_HANDLES "Server has open handles"
1812 'ERROR_RESOURCE_DATA_NOT_FOUND "Resource data not found"
1813 'ERROR_RESOURCE_TYPE_NOT_FOUND "Resource type not found"
1814 'ERROR_RESOURCE_NAME_NOT_FOUND "Resource name not found"
1815 'ERROR_RESOURCE_LANG_NOT_FOUND "Resource language not found"
1816 'ERROR_NOT_ENOUGH_QUOTA "Not enough quota"
1901 'ERROR_INVALID_TIME "Invalid time"
1902 'ERROR_INVALID_FORM_NAME "Invalid form name"
1903 'ERROR_INVALID_FORM_SIZE "Invalid form size"
1904 'ERROR_ALREADY_WAITING "Already awaiting printer handle"
1905 'ERROR_PRINTER_DELETED "Printer deleted"
1906 'ERROR_INVALID_PRINTER_STATE "Invalid printer state"
1907 'ERROR_PASSWORD_MUST_CHANGE "User must change password"
1908 'ERROR_DOMAIN_CONTROLLER_NOT_FOUND "Domain controller not found"
1909 'ERROR_ACCOUNT_LOCKED_OUT "Account locked out"
1919 'ERROR_NO_SITENAME "No site name available"
1920 'ERROR_CANT_ACCESS_FILE "The file cannot be accessed"
1921 'ERROR_CANT_RESOLVE_FILENAME "The filename cannot be resolved"
2250 'ERROR_NOT_CONNECTED "This network connection does not exist"
))
